pipeline{
	agent any
	tools { 
        maven 'maven 3.9.9' 
        jdk 'Java JDK 17' 
    }
	stages{
		stage("clean"){
			steps{
				echo "Start Clean"
				bat "mvn -f CT_Assignment/pom.xml clean"
			}
		}
		stage("test"){
			steps{
				echo "Start Test"
				bat "mvn -f CT_Assignment/pom.xml test"
			}
		}
		stage("build"){
			steps{
				echo "Start build"
				bat "mvn -f CT_Assignment/pom.xml install -DskipTests"
			}
		}
	}
} 
